name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Test Formula
        run: |
          mkdir -p /opt/homebrew/Library/Taps/tirano-tirano/homebrew-crules
          cp Formula/crules.rb /opt/homebrew/Library/Taps/tirano-tirano/homebrew-crules/
          brew audit --strict tirano-tirano/crules/crules
          brew style Formula/crules.rb

  update-sha:
    needs: test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update SHA
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          curl -L "https://github.com/tirano-tirano/crules/archive/refs/tags/${VERSION}.tar.gz" | shasum -a 256 | cut -d ' ' -f 1 > sha.txt
          sed -i "s/sha256 \"placeholder\"/sha256 \"$(cat sha.txt)\"/" Formula/crules.rb

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add Formula/crules.rb
          git commit -m "Update SHA for version ${GITHUB_REF#refs/tags/}"
          git push
