name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-crules
        uses: actions/checkout@v4
        with:
          repository: tirano-tirano/homebrew-crules
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-crules

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update Formula
        run: |
          cd homebrew-crules
          VERSION=${GITHUB_REF#refs/tags/v}
          TARBALL_URL="https://github.com/tirano-tirano/crules/archive/refs/tags/v${VERSION}.tar.gz"
          SHA256=$(curl -L $TARBALL_URL | shasum -a 256 | cut -d ' ' -f 1)

          # Update version and sha256 in Formula
          sed -i "s|url.*|url \"$TARBALL_URL\"|" Formula/crules.rb
          sed -i "s|sha256.*|sha256 \"$SHA256\"|" Formula/crules.rb

          git add Formula/crules.rb
          git commit -m "Update formula for version ${VERSION}"
          git push
